/** Declaration file generated by dts-gen */

export function scopeFocus(element: any): void;

export function unscopeFocus(): void;

export namespace scopeFocus {
    const prototype: {
    };

}

export namespace unscopeFocus {
    const prototype: {
    };

}

